LOGOUT_REDIRECT_URL='index'
LOGIN_REDIRECT_URL='index'
LOGIN_URL='auth_login'

ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_EMAIL_SUBJECT_PREFIX = '[Cloudberry App]'
# SEND_ACTIVATION_EMAIL = False
REGISTRATION_AUTO_LOGIN = True
LOGIN_REDIRECT_URL = '/'
