# Generated by Django 2.0.6 on 2018-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_radius', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusaccounting',
            name='start_delay',
            field=models.IntegerField(blank=True, db_column='acctstartdelay', null=True, verbose_name='Start delay'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='stop_delay',
            field=models.IntegerField(blank=True, db_column='acctstopdelay', null=True, verbose_name='Stop delay'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='x_ascend_session_svr_key',
            field=models.CharField(blank=True, db_column='xascendsessionsvrkey', max_length=10, null=True, verbose_name='realm'),
        ),
    ]
