# Generated by Django 2.0.6 on 2018-06-30 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0005_remove_device_generated_image_id'),
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloudberry_radius', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp', verbose_name='Time')),
                ('latest', models.BooleanField()),
                ('cost_per_byte', models.FloatField(blank=True, db_column='cost', null=True, verbose_name='Cost per byte')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_pricing', to='auth.ConfigurationGroup')),
            ],
            options={
                'db_table': 'radprice',
            },
        ),
        migrations.RemoveField(
            model_name='radiusaccounting',
            name='username',
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='amount',
            field=models.FloatField(blank=True, db_column='amount', null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='device',
            field=models.ForeignKey(blank=True, db_column='nasidentifier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_accounting', to='cloudberry_app.Device'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='start_delay',
            field=models.IntegerField(blank=True, db_column='acctstartdelay', null=True, verbose_name='Start delay'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='stop_delay',
            field=models.IntegerField(blank=True, db_column='acctstopdelay', null=True, verbose_name='Stop delay'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_accounting', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='withdrawal_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='auth.ConfigurationGroup'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='x_ascend_session_svr_key',
            field=models.CharField(blank=True, db_column='xascendsessionsvrkey', max_length=10, null=True, verbose_name='realm'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_ip_address',
            field=models.GenericIPAddressField(blank=True, db_column='nasipaddress', db_index=True, null=True, verbose_name='NAS IP address'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='session_id',
            field=models.CharField(blank=True, db_column='acctsessionid', db_index=True, max_length=64, null=True, verbose_name='session ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='unique_id',
            field=models.CharField(blank=True, db_column='acctuniqueid', max_length=32, null=True, unique=True, verbose_name='accounting unique ID'),
        ),
    ]
