# Generated by Django 2.0.6 on 2018-07-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_radius', '0002_auto_20180630_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='cost_per_byte',
            field=models.FloatField(db_column='cost', default=1, verbose_name='Cost per byte'),
            preserve_default=False,
        ),
    ]
