# Generated by Django 2.0.6 on 2018-06-29 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloudberry_radius', '0003_radiusaccounting_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiusaccounting',
            name='username',
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
