# Generated by Django 2.0.6 on 2018-06-29 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_radius', '0004_auto_20180629_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiusaccounting',
            name='device',
            field=models.ForeignKey(blank=True, db_column='nasidentifier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_accounting', to='cloudberry_app.Device'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_accounting', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
