# Generated by Django 2.0.6 on 2018-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_radius', '0005_auto_20180629_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_ip_address',
            field=models.GenericIPAddressField(blank=True, db_column='nasipaddress', db_index=True, null=True, verbose_name='NAS IP address'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='session_id',
            field=models.CharField(blank=True, db_column='acctsessionid', db_index=True, max_length=64, null=True, verbose_name='session ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='unique_id',
            field=models.CharField(blank=True, db_column='acctuniqueid', max_length=32, null=True, unique=True, verbose_name='accounting unique ID'),
        ),
    ]
