# Generated by Django 2.0.6 on 2018-06-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0005_remove_device_generated_image_id'),
        ('cloudberry_radius', '0006_auto_20180629_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_column='timestamp', verbose_name='Time')),
                ('cost_per_byte', models.FloatField(blank=True, db_column='cost', null=True, verbose_name='Cost per byte')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_pricing', to='cloudberry_app.Device')),
                ('latest_price_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radius_latest_price', to='cloudberry_app.Device')),
            ],
            options={
                'db_table': 'radprice',
            },
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='cost',
            field=models.FloatField(blank=True, db_column='cost', null=True, verbose_name='Cost'),
        ),
    ]
