# Generated by Django 2.0.6 on 2018-06-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_radius', '0008_auto_20180629_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='device',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='latest_price',
            new_name='latest',
        ),
    ]
