# Generated by Django 2.0.6 on 2018-06-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('cloudberry_radius', '0010_auto_20180629_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusaccounting',
            name='withdrawal_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='auth.ConfigurationGroup'),
        ),
    ]
