# Generated by Django 2.0.3 on 2018-03-15 13:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0002_auto_20180315_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='template',
        ),
        migrations.AlterField(
            model_name='backend',
            name='backend',
            field=models.CharField(blank=True, choices=[('netjsonconfig.OpenWrt', 'OpenWRT/LEDE'), ('netjsonconfig.OpenWisp', 'OpenWISP Firmware 1.x')], help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='schema',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='JSONSchema for the configuration', verbose_name='schema'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='transform',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='<a href="https://github.com/dvdln/jsonpath-object-transform">jsonpath-object-transform</a>to transform the schema to that of the back-end and/or template', verbose_name='transform'),
        ),
        migrations.AlterField(
            model_name='config',
            name='backend',
            field=models.CharField(blank=True, help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
    ]
