# Generated by Django 2.0.6 on 2018-06-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0003_auto_20180605_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='generated_image_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
