# Generated by Django 2.0.3 on 2018-03-21 12:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0003_auto_20180315_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedtemplate',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedtemplate',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='template',
            name='vpn',
        ),
        migrations.RemoveField(
            model_name='vpn',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='vpn',
            name='cert',
        ),
        migrations.AlterUniqueTogether(
            name='vpnclient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vpnclient',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='vpnclient',
            name='config',
        ),
        migrations.RemoveField(
            model_name='vpnclient',
            name='vpn',
        ),
        migrations.AlterModelOptions(
            name='config',
            options={},
        ),
        migrations.RemoveField(
            model_name='backend',
            name='template',
        ),
        migrations.RemoveField(
            model_name='config',
            name='device',
        ),
        migrations.RemoveField(
            model_name='config',
            name='last_ip',
        ),
        migrations.RemoveField(
            model_name='config',
            name='status',
        ),
        migrations.RemoveField(
            model_name='config',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='config',
            name='vpn',
        ),
        migrations.AddField(
            model_name='config',
            name='devices',
            field=models.ManyToManyField(related_name='configs', to='cloudberry_app.Device'),
        ),
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backend',
            name='backend',
            field=models.CharField(blank=True, choices=[('/cloudberry_app/schema/transform/backend/netjsonconfig.OpenWrt', 'OpenWRT/LEDE'), ('/cloudberry_app/schema/transform/backend/netjsonconfig.OpenWisp', 'OpenWISP Firmware 1.x')], help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
        migrations.AlterField(
            model_name='config',
            name='backend',
            field=models.CharField(blank=True, choices=[('/cloudberry_app/schema/backend/netjsonconfig.OpenWrt', 'OpenWRT/LEDE'), ('/cloudberry_app/schema/backend/netjsonconfig.OpenWisp', 'OpenWISP Firmware 1.x'), ('/cloudberry_app/schema/dynamic/232d8f4b-49d5-4d5f-be84-fdaba6a28623', 'MyTemplate'), ('/cloudberry_app/schema/dynamic/47cd6f16-f110-4ddc-86ff-a3dfc6171637', 'Template2'), ('/cloudberry_app/schema/dynamic/8c985117-a2c9-4370-9b72-d57af1d05794', 'NanaXXXX')], help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
        migrations.AlterField(
            model_name='config',
            name='config',
            field=jsonfield.fields.JSONField(default=dict, help_text='configuration in NetJSON DeviceConfiguration format', verbose_name='configuration'),
        ),
        migrations.DeleteModel(
            name='TaggedTemplate',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TemplateTag',
        ),
        migrations.DeleteModel(
            name='Vpn',
        ),
        migrations.DeleteModel(
            name='VpnClient',
        ),
    ]
