# Generated by Django 2.0.6 on 2018-06-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0004_device_generated_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='generated_image_id',
        ),
    ]
