# Generated by Django 2.0.6 on 2018-07-01 18:42

import cloudberry_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0005_remove_device_generated_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='backend',
            field=models.CharField(choices=[('/cloudberry_app/schema/backend/cloudberry_netjson.OpenWrt', 'OpenWRT/Cloudberry'), ('/cloudberry_app/schema/backend/netjsonconfig.OpenWrt', 'OpenWRT/LEDE'), ('/cloudberry_app/schema/backend/netjsonconfig.OpenWisp', 'OpenWISP Firmware 1.x')], default='/cloudberry_app/schema/backend/cloudberry_netjson.OpenWrt', help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_image',
            field=cloudberry_app.fields.DynamicTextListField(help_text='Select OS image', max_length=128, verbose_name='os image'),
        ),
    ]
