# Generated by Django 2.0.3 on 2018-03-21 15:03

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0005_device_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, help_text='indicates the last ip from which the configuration was downloaded from (except downloads from this page)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='modified', help_text='modified means the configuration is not applied yet; running means applied and running; error means the configuration caused issues and it was rolledback', max_length=100, no_check_for_status=True),
        ),
    ]
