# Generated by Django 2.0.3 on 2018-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberry_app', '0007_auto_20180323_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='backend',
            field=models.CharField(blank=True, choices=[('/cloudberry_app/schema/backend/cloudberry_netjson.OpenWrt', 'OpenWRT/Cloudberry'), ('/cloudberry_app/schema/backend/netjsonconfig.OpenWrt', 'OpenWRT/LEDE'), ('/cloudberry_app/schema/backend/netjsonconfig.OpenWisp', 'OpenWISP Firmware 1.x'), ('/cloudberry_app/schema/dynamic/232d8f4b-49d5-4d5f-be84-fdaba6a28623', 'MyTemplate'), ('/cloudberry_app/schema/dynamic/47cd6f16-f110-4ddc-86ff-a3dfc6171637', 'Template2'), ('/cloudberry_app/schema/dynamic/8c985117-a2c9-4370-9b72-d57af1d05794', 'NanaXXXX'), ('/cloudberry_app/schema/dynamic/4560bc02-d7d7-405e-9fd8-95f61f8d39b1', 'CloudberryVPN'), ('/cloudberry_app/schema/dynamic/e20ec3c9-69ed-4317-9bb5-3354c989713d', 'CloudberryVPNDockerManager')], help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
    ]
