# Generated by Django 2.0.3 on 2018-04-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_configurationgroup'),
        ('cloudberry_app', '0009_auto_20180328_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.ConfigurationGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.ConfigurationGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.ConfigurationGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='backend',
            field=models.CharField(blank=True, choices=[('/cloudberry/cloudberry_app/schema/backend/cloudberry_netjson.OpenWrt', 'OpenWRT/Cloudberry'), ('/cloudberry/cloudberry_app/schema/backend/netjsonconfig.OpenWrt', 'OpenWRT/LEDE'), ('/cloudberry/cloudberry_app/schema/backend/netjsonconfig.OpenWisp', 'OpenWISP Firmware 1.x')], help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
    ]
