# Generated by Django 2.0.5 on 2018-05-02 14:32

from django.db import migrations, models

from django_admin_ownership.cross_app_migrations import WithAppLabelOperation

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        WithAppLabelOperation(
            'auth',
            migrations.CreateModel(
                name='ConfigurationGroup',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                    ('group', models.ForeignKey(blank=True, null=True, on_delete='cascade', to='auth.ConfigurationGroup')),
                    ('read', models.ManyToManyField(blank=True, related_name='read_devices', to='auth.Group')),
                    ('write', models.ManyToManyField(blank=True, related_name='write_devices', to='auth.Group')),
                ],
                options={
                    'verbose_name': 'Configuration group',
                },
            )
        ),
    ]
