# Generated by Django 2.0.6 on 2018-06-25 13:16

from django.conf import settings
from django.db import migrations, models
from django_admin_ownership.cross_app_migrations import WithAppLabelOperation


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_ownership', '0001_initial'),
    ]

    operations = [
        WithAppLabelOperation(
            'auth',
            migrations.AddField(
                model_name='configurationgroup',
                name='owner',
                field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
            )
        ),
    ]
