# Generated by Django 2.0.6 on 2018-06-25 14:46

from django.db import migrations, models
import django.db.models.deletion
from django_admin_ownership.cross_app_migrations import WithAppLabelOperation


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_ownership', '0002_configurationgroup_owner'),
    ]

    operations = [
        WithAppLabelOperation(
            'auth',
            migrations.AddField(
                model_name='group',
                name='group',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_user_group', to='auth.ConfigurationGroup'),
            )
        ),
    ]
